[Preferences]
WebUI\Enabled=true
WebUI\Address=*
WebUI\Port=8080
WebUI\HostHeaderValidation=true
WebUI\ServerDomains=qbittorrent;localhost
WebUI\CSRFProtection=true
WebUI\LocalHostAuth=true
WebUI\AuthSubnetWhitelistEnabled=false
WebUI\ReverseProxySupportEnabled=false
WebUI\HTTPS\Enabled=false

[Network]
Proxy\Type=HTTP
Proxy\IP=newgreedy
Proxy\Port=3456
Proxy\AuthEnabled=false
Proxy\HostnameLookupEnabled=true
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\RSS=false
Proxy\Profiles\Misc=false

[BitTorrent]
Session\ProxyPeerConnections=false
Session\DefaultSavePath=/data
